apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: {{ .Release.Name }}-experiment
spec:
  templates:
    - name: version-a
      replicas: 1
      template:
        metadata:
          labels:
            version: "A"
        spec:
          containers:
            - name: {{ .Values.app.name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tagA }}
              ports:
                - containerPort: 80
    - name: version-b
      replicas: 1
      template:
        metadata:
          labels:
            version: "B"
        spec:
          containers:
            - name: {{ .Values.app.name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tagB }}
              ports:
                - containerPort: 80
