apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: ab-experiment
  namespace: nginx-ab-helm
spec:
  duration: 30s  # Minimum time the experiment should run
  terminate: true  # This can be used to indicate that the experiment should terminate
  templates:
    - name: version-a
      replicas: 1
      selector:
        matchLabels:
          version: A
      template:
        metadata:
          labels:
            version: A
        spec:
          containers:
            - name: nginx
              image: nginx:1.26.1
              ports:
                - containerPort: 80