apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: ab-experiment-new
  namespace: nginx-ab-helm
spec:
  duration: 30s  # Experiment duration
  terminate: true
  templates:
    - name: version-a
      replicas: 1
      selector:
        matchLabels:
          version: A
      template:
        metadata:
          labels:
            version: A
        spec:
          containers:
            - name: nginx
              image: nginx:1.26.1
              ports:
                - containerPort: 80
    - name: version-b
      replicas: 1
      selector:
        matchLabels:
          version: B
      template:
        metadata:
          labels:
            version: B
        spec:
          containers:
            - name: nginx
              image: nginx:1.26.2
              ports:
                - containerPort: 80
