apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysis-template
spec:
  metrics:
    - name: success-rate
      interval: 1m
      count: 3
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(http_requests_total{job="nginx",status=~"2.."}[1m]))
