apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-ab-rollout
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      stableService: {{ .Release.Name }}-stable
      canaryService: {{ .Release.Name }}-canary
      trafficRouting:
        alb:
          ingress: {{ $fullName }}
          servicePort: 80
      steps:
        - setWeight: 50
        - pause: {duration: 60s}
        - setWeight: 100
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80
