apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-ab-rollout
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      steps:
        - setWeight: 20  # Route 20% of traffic to canary version
        - pause: {duration: 10s}
        - setWeight: 50  # Route 50% of traffic to canary version
        - pause: {duration: 10s}
        - experiment:
            templates:
              - name: version-a
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      version: A
                  template:
                    metadata:
                      labels:
                        version: A
                    spec:
                      containers:
                        - name: nginx
                          image: nginx:1.26.1
                          ports:
                            - containerPort: 80
            analyses:
              - name: version-a-analysis
                templateName: analysis-template
        - setWeight: 100  # Finally switch all traffic to canary
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
