apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-ab-rollout
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      steps:
        - setWeight: 50  # Send 50% of traffic to version A and 50% to version B
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: version-a
          image: {{ .Values.versionA.image.repository }}:{{ .Values.versionA.image.tag }}
          ports:
            - containerPort: 80
        - name: version-b
          image: {{ .Values.versionB.image.repository }}:{{ .Values.versionB.image.tag }}
          ports:
            - containerPort: 8080
