apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-ab-rollout
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      steps:
        - setWeight: 50  # Split traffic
        - experiment:
          templates:
          - name: canary
            specRef: canary
          analyses:
          - name: random-fail
            templateName: random-fail
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
