apiVersion: v1
kind: Service
metadata:
  name: {{ include "ab-helm.fullname" . }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
