apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-bluegreen
  namespace: nginx-blue-green
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: nginx-active
      previewService: nginx-preview
      autoPromotionEnabled: false # Set to true for automatic promotion
      scaleDownDelaySeconds: 30   # Delay before scaling down the old version
  selector:
    matchLabels:
      app: nginx-bluegreen
  template:
    metadata:
      labels:
        app: nginx-bluegreen
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.1  # Initial version of the image
          ports:
            - containerPort: 80
