apiVersion: v1
kind: Service
metadata:
  name: nginx-bluegreen-service
  namespace: nginx-blue-green
spec:
  selector:
    app: nginx-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
