apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-primary
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    version: v1
spec:
  replicas: {{ .Values.primary.replicaCount }}
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.primary.image.repository }}:{{ .Values.primary.image.tag }}"
          imagePullPolicy: {{ .Values.primary.image.pullPolicy }}
          ports:
            - containerPort: 80
