apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
