apiVersion: v1
kind: Service
metadata:
  name: nginx-rolling-service
  namespace: nginx-rolling
spec:
  selector:
    app: nginx-rolling-update
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
