{{- if and .Values.rollout.create (eq .Values.rollout.strategy "canary") }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "rollout-templates.fullname" . }}
  labels:
    {{- include "rollout-templates.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "rollout-templates.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rollout-templates.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
  strategy:
    canary:
      steps:
        {{- range .Values.rollout.canary.steps }}
        {{- if .setWeight }}
        - setWeight: {{ .setWeight }}
        {{- end }}
        {{- if .pause }}
        - pause:
            {{- if .pause.duration }}
            duration: {{ .pause.duration }}
            {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
