{{- if or (not .Values.rollout.create) (not (eq .Values.rollout.strategy "blueGreen")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-templates.fullname" . }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
{{- end }}