{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "rollout-templates.fullname" . }}
  labels:
    {{- include "rollout-templates.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if and .Values.strategy (.Values.strategy.enabled) }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ template "rollout-templates.fullname" . }}
  {{- if .Values.hpa.minReplicas }}
  minReplicas: {{ toYaml .Values.hpa.minReplicas }}
  {{- end }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.memory }}
  {{- end }}
  {{- if .Values.hpa.requests }}
  - type: Pods
    pods:
      metric:
        name: http_requests
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.requests }}
  {{- end }}
{{- end }}
