{{- if and .Values.rollout.create (eq .Values.rollout.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-templates.fullname" . }}-preview
  labels:
    app.kubernetes.io/instance: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-templates.selectorLabels" . | nindent 4 }}
{{- end }}