{{- if and .Values.strategy (.Values.strategy.enabled) (eq .Values.strategy.type "blueGreen") }}
  {{- $services := list (include "rollout-templates.fullname" .) (printf "%s-preview" (include "rollout-templates.fullname" .)) }}
  {{- range $services }}
---
# Service for Blue-Green (Active or Preview)
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rollout-templates.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  {{ if $.Values.service.loadBalancerClass -}}
  loadBalancerClass: {{ $.Values.service.loadBalancerClass }}
  {{- end }}
  ports:
    {{- range $.Values.service.ports }}
      - name: {{ .name }}
        targetPort: {{ .targetPort }}
        port: {{ .port }}
        protocol: {{ .protocol }}
      {{- end }}
  selector:
    {{- include "rollout-templates.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- else }}
# Default Service (if strategy is not enabled or not blueGreen)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-templates.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rollout-templates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerClass -}}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  ports:
    {{- range $.Values.service.ports }}
      - name: {{ .name }}
        targetPort: {{ .targetPort }}
        port: {{ .port }}
        protocol: {{ .protocol }}
      {{- end }}
  selector:
    {{- include "rollout-templates.selectorLabels" . | nindent 4 }}
{{- end }}