{{- if and .Values.strategy.enabled (eq .Values.strategy.type "blueGreen") }}
  {{- $services := list (include "rollout-templates.fullname" .) (printf "%s-preview" (include "rollout-templates.fullname" .)) }}
  {{- range $services }}
---
# Service for Blue-Green (Active or Preview)
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  labels:
    {{- include "rollout-templates.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-templates.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- else }}
# Default Service (if strategy is not enabled or not blueGreen)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-templates.fullname" . }}
  labels:
    {{- include "rollout-templates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-templates.selectorLabels" . | nindent 4 }}
{{- end }}
